
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dlh_core_packages'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'dlh_core_packages'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models


# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  dlh_core_packages:
    # Config indicated by + and applies to all files under models/example/
    example:
      +materialized: view
  dlh_quickbooks:
    source_database: DEVELOPER_SANDBOX
    source_schema: DEMO_QUICKBOOKS_SANDBOX
    target_schema: QUICKBOOKS
  dlh_salesforce:
    source_database: DEVELOPER_SANDBOX
    source_schema: DEMO_SALESFORCE
    target_schema: SALESFORCE
  dlh_square:
    source_database: DEVELOPER_SANDBOX
    source_schema: DEMO_SQUARE_ALT13
    target_schema: SQUARE
  dlh_stripe:
    source_database: DEVELOPER_SANDBOX
    source_schema: DEMO_STRIPE_NEW
    target_schema: STRIPE
  dlh_xero:
    source_database: DEVELOPER_SANDBOX
    source_schema: DEMO_XERO
    target_schema: XERO